linters-settings:
  goimports:
    local-prefixes: github.pie.apple.com,go.apple.com
  lll:
    line-length: 180

linters:
  disable-all: false
  enable:
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert
    - whitespace
    - wsl
  disable:
    - structcheck
    - revive
